backend:
  name: git-gateway
  branch: master

media_folder: static/media
public_folder: /media
locale: 'de'

collections:
  - name: 'bilder'
    label: 'Bilder'
    label_singular: 'Bild'
    format: 'json'
    folder: 'content/bilder'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Entstehungsjahr', name: 'date', widget: 'datetime', date_format: 'YYYY', time_format: '' }
      - { label: 'Beschreibung', name: 'description', widget: 'string', required: false }
      - { label: 'Technik', name: 'technique', widget: 'string' }
      - { label: 'Maße', name: 'dimensions', widget: 'string', pattern: ['\d+ x \d+', 'Muss dem Format \'<Breite> x <Höhe>\' folgen']}
      - { label: 'Bild', name: 'image', widget: 'image' }